-- Baseline Database Migration marker
-- Version: 0001
-- Description: Existing production database baseline.
--
-- IMPORTANT:
-- This migration intentionally contains no SQL statements.
-- Existing production tables and data must remain untouched.